name = x_player_armor
title = X Player Armor
author = SaKeL
description = High-performance modular player armor and shield system attaching lightweight visual entities directly to skeletal bones with zero tick overhead.
min_luanti_version = 5.10.0
depends =
optional_depends = default, player_api, x_player_api, sfinv, unified_inventory, i3, bones, player_monoids, pova, ethereal, moreores, nether, technic, 3d_armor, shields, 3d_armor_stand, 3d_armor_ui, 3d_armor_sfinv, 3d_armor_ip, wieldview, armor_admin, armor_bronze, armor_cactus, armor_crystal, armor_diamond, armor_gold, armor_mithril, armor_nether, armor_steel, armor_wood, armor_leather, armor_woven

